#yaml document start with ----
---
- #this minus is required in yaml it indicate list of items. Playbook contains a list of play and every play will be a dictionary
#host: where you want to run your playbook
  hosts: jump
  
#vars: variable that will apply to the play
  vars: #is a keywoad
    myurl: "https://releases.ansible.com/ansible/ansible-2.9.9.tar.gz"
    mycrc: "sha256:https://releases.ansible.com/ansible/ansible-2.9.9.tar.gz.sha"
    mydest: "/tmp/"
  tasks: 
  - name: update my system
    apt:
      update_cache: yes
  - name: install prerequsitis
    apt:
      name: 
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      update_cache: yes
  - name: add docker gpg key 
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: add the docker repo 
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io 
        - docker-compose-plugin
  - name: add userpermission
    shell: "usermod -aG docker {{lookup('env','USER')}}"
  - name: install python package manage
    apt:
      name: python3-pip